/** Generated by scripts/sync-egys.mjs; do not edit by hand. */
export const egysContractHash =
  "43c26f8ad2bff683a001821330cd1f0b2e80ab6b47089d324c878634d92f583e" as const;
export const egysAuthContract = {
  mode: "provider-id-token-exchange",
  providersPath: "/api/v1/auth/providers",
  signInPath: "/api/v1/auth/{provider}",
  requestBody: ["idToken"],
  sessionCookie: "HttpOnly",
  callbackRoutes: [],
} as const;
export const egysApiRoutes = [
  {
    method: "GET",
    path: "/api/v1/attendance/services",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/ops/attendance/AttendanceController.java",
  },
  {
    method: "POST",
    path: "/api/v1/attendance/services",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/ops/attendance/AttendanceController.java",
  },
  {
    method: "POST",
    path: "/api/v1/attendance/services/{serviceId}/convert-to-named",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/ops/attendance/AttendanceController.java",
  },
  {
    method: "GET",
    path: "/api/v1/attendance/services/{serviceId}/present",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/ops/attendance/AttendanceController.java",
  },
  {
    method: "PUT",
    path: "/api/v1/attendance/services/{serviceId}/present",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/ops/attendance/AttendanceController.java",
  },
  {
    method: "DELETE",
    path: "/api/v1/attendance/services/{serviceId}/present/{personId}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/ops/attendance/AttendanceController.java",
  },
  {
    method: "POST",
    path: "/api/v1/auth/{provider}",
    authentication: "public",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "POST",
    path: "/api/v1/auth/language",
    authentication: "session",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "GET",
    path: "/api/v1/auth/me",
    authentication: "public",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "GET",
    path: "/api/v1/auth/providers",
    authentication: "public",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "POST",
    path: "/api/v1/auth/signout",
    authentication: "public",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "POST",
    path: "/api/v1/auth/whatsapp/start",
    authentication: "public",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "GET",
    path: "/api/v1/auth/whatsapp/state",
    authentication: "public",
    source: "backend/src/main/java/id/gys/egys/auth/web/AuthController.java",
  },
  {
    method: "GET",
    path: "/api/v1/branches",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/branch/BranchController.java",
  },
  {
    method: "GET",
    path: "/api/v1/families",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/family/FamilyController.java",
  },
  {
    method: "POST",
    path: "/api/v1/families",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/family/FamilyController.java",
  },
  {
    method: "DELETE",
    path: "/api/v1/families/{id}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/family/FamilyController.java",
  },
  {
    method: "GET",
    path: "/api/v1/families/{id}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/family/FamilyController.java",
  },
  {
    method: "PUT",
    path: "/api/v1/families/{id}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/family/FamilyController.java",
  },
  {
    method: "GET",
    path: "/api/v1/families/{id}/tree",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/family/FamilyController.java",
  },
  {
    method: "GET",
    path: "/api/v1/members",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/MemberController.java",
  },
  {
    method: "POST",
    path: "/api/v1/members",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/MemberController.java",
  },
  {
    method: "GET",
    path: "/api/v1/members/{id}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/MemberController.java",
  },
  {
    method: "PUT",
    path: "/api/v1/members/{id}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/MemberController.java",
  },
  {
    method: "DELETE",
    path: "/api/v1/members/{personId}/attachments/{kind}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/attachment/MemberAttachmentController.java",
  },
  {
    method: "GET",
    path: "/api/v1/members/{personId}/attachments/{kind}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/attachment/MemberAttachmentController.java",
  },
  {
    method: "PUT",
    path: "/api/v1/members/{personId}/attachments/{kind}",
    authentication: "session",
    source:
      "backend/src/main/java/id/gys/egys/core/person/attachment/MemberAttachmentController.java",
  },
  {
    method: "GET",
    path: "/api/v1/meta/build",
    authentication: "session",
    source: "backend/src/main/java/id/gys/egys/meta/BuildController.java",
  },
  {
    method: "GET",
    path: "/api/v1/meta/flags",
    authentication: "session",
    source: "backend/src/main/java/id/gys/egys/flags/FlagsController.java",
  },
  {
    method: "GET",
    path: "/api/v1/webhooks/whatsapp",
    authentication: "public",
    source:
      "backend/src/main/java/id/gys/egys/auth/whatsapp/WhatsAppWebhookController.java",
  },
  {
    method: "POST",
    path: "/api/v1/webhooks/whatsapp",
    authentication: "public",
    source:
      "backend/src/main/java/id/gys/egys/auth/whatsapp/WhatsAppWebhookController.java",
  },
  {
    method: "POST",
    path: "/api/v1/webhooks/whatsapp/bot",
    authentication: "public",
    source:
      "backend/src/main/java/id/gys/egys/auth/whatsapp/BotWebhookController.java",
  },
] as const;
