/** Generated by scripts/generate-fork-pdf-manifest.mjs; do not edit by hand. */
export const forkPdfSource = {
  sourceRepo: "ThenGB/GYSAPP-Fork",
  sourceCommit: "4f0d39b",
  masterPath: "assets/data/pdf/kr/kr_master.pdf",
  sizeBytes: 4770376,
  sha256: "5ea1d857cac8a8d52600052ef3a7b22214919ffaefe4f0f97c71d6f57f5f8805",
} as const;
