from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, got {count}: {old[:120]!r}")
    file.write_text(text.replace(old, new, 1))


media = "apps/web/e2e/media-load.spec.ts"
replace_once(
    media,
    '''  await page\n    .getByRole("link", { name: /Kitab Markus/i })\n    .first()\n    .click();\n  await expect(page.getByRole("heading", { name: "Kitab Markus" })).toBeVisible(\n    {\n      timeout: 15_000,\n    },\n  );\n  await page.getByRole("button", { name: "Baca di aplikasi" }).click();\n  await expect(page.getByRole("alert")).toContainText(\n    "PDF belum dapat dibuka",\n    {\n      timeout: 20_000,\n    },\n  );''',
    '''  await page\n    .getByRole("link", { name: /Kitab Markus/i })\n    .first()\n    .click();\n  await expect(page).toHaveURL(/\\/literatur\\/.+\\?read=1$/);\n  await expect(page.getByRole("alert")).toContainText(\n    "PDF belum dapat dibuka",\n    {\n      timeout: 20_000,\n    },\n  );''',
)
replace_once(
    media,
    '''  await page.goto("/GYSApp-Tauri/literatur");\n  await page\n    .getByRole("link", { name: /Kitab Markus/i })\n    .first()\n    .click();\n  await expect(page.getByRole("heading", { name: "Kitab Markus" })).toBeVisible(\n    { timeout: 15_000 },\n  );\n  await page.getByRole("button", { name: "Baca di aplikasi" }).click();\n  await expect(page.locator(".pdf-reader")).toBeVisible({ timeout: 30_000 });\n  await expect(page.locator(".pdf-toolbar")).toContainText("Page 1 / 1");\n  await expect(page).toHaveURL(/\\/literatur\\//);\n\n  await page.getByRole("button", { name: "Tutup" }).click();\n  await expect(page.locator(".pdf-reader")).toHaveCount(0);\n  await expect(\n    page.getByRole("button", { name: "Lanjutkan dari halaman 1" }),\n  ).toBeVisible();\n  await page.getByRole("button", { name: "Lanjutkan dari halaman 1" }).click();\n  await expect(page.locator(".pdf-reader")).toBeVisible({ timeout: 30_000 });\n  await expect(page.locator(".pdf-toolbar")).toContainText("Page 1 / 1");''',
    '''  await page.goto("/GYSApp-Tauri/literatur");\n  const markus = page.getByRole("link", { name: /Kitab Markus/i }).first();\n  await markus.click();\n  await expect(page).toHaveURL(/\\/literatur\\/.+\\?read=1$/);\n  await expect(page.locator(".pdf-reader")).toBeVisible({ timeout: 30_000 });\n  await expect(page.locator(".pdf-toolbar")).toContainText("Page 1 / 1");\n\n  await page.getByRole("button", { name: "Tutup" }).click();\n  await expect(page).toHaveURL(/\\/literatur$/);\n  await expect(page.locator(".pdf-reader")).toHaveCount(0);\n  const resume = page.getByRole("link", { name: /Kitab Markus/i }).first();\n  await expect(resume).toContainText(/Lanjut.*halaman 1/i);\n  await resume.click();\n  await expect(page.locator(".pdf-reader")).toBeVisible({ timeout: 30_000 });\n  await expect(page.locator(".pdf-toolbar")).toContainText("Page 1 / 1");''',
)

smoke = "apps/web/e2e/smoke.spec.ts"
replace_once(
    smoke,
    '''test("faith topics search, select, and persist a personal note", async ({\n  page,\n}) => {\n  await page.goto("/GYSApp-Tauri/iman");\n  await expect(\n    page.getByRole("region", { name: "Dasar Kepercayaan" }),\n  ).toBeVisible();\n  const rows = page.locator(".faith-row-heading");\n  await expect(rows.first()).toBeVisible({ timeout: 15_000 });\n  const initialCount = await rows.count();\n  expect(initialCount).toBeGreaterThan(0);\n\n  // The vertical list keeps one active selection at a time.\n  await rows.nth(1).click();\n  await expect(rows.nth(1)).toHaveAttribute("aria-pressed", "true");\n  await expect(rows.first()).toHaveAttribute("aria-pressed", "false");\n\n  // Search filters the list using real content.\n  await page.getByLabel("Cari pokok iman").fill("Allah");\n  await expect\n    .poll(async () => page.locator(".faith-row-heading").count())\n    .toBeLessThan(initialCount);\n\n  // A note on the selected topic persists across reloads.\n  await page.getByLabel("Cari pokok iman").fill("");\n  await page\n    .getByRole("dialog", { name: /Pokok/ })\n    .getByRole("button", { name: "Catatan pribadi" })\n    .click();\n  await page\n    .getByLabel("Catatan pribadi")\n    .fill("Renungan dari pokok dasar kepercayaan.");\n  await page.getByRole("button", { name: "Simpan catatan" }).click();\n  await expect(\n    page.getByRole("status").filter({ hasText: "disimpan" }),\n  ).toBeVisible();\n  await page.reload();\n  await expect(\n    page.getByRole("region", { name: "Dasar Kepercayaan" }),\n  ).toBeVisible({\n    timeout: 15_000,\n  });\n  // The note is keyed per topic, so reopen the same topic after the reload.\n  await page.locator(".faith-row-heading").nth(1).click();\n  await page\n    .getByRole("dialog", { name: /Pokok/ })\n    .getByRole("button", { name: "Catatan pribadi" })\n    .click();\n  await expect(page.getByLabel("Catatan pribadi")).toHaveValue(\n    "Renungan dari pokok dasar kepercayaan.",\n  );\n});''',
    '''test("faith topics search, open summary, and persist a personal note", async ({\n  page,\n}) => {\n  await page.goto("/GYSApp-Tauri/iman");\n  await expect(\n    page.getByRole("region", { name: "Dasar Kepercayaan" }),\n  ).toBeVisible();\n  const rows = page.locator(".faith-row-heading");\n  await expect(rows.first()).toBeVisible({ timeout: 15_000 });\n  const initialCount = await rows.count();\n  expect(initialCount).toBeGreaterThan(0);\n\n  // Search filters the list using real content without changing the direct-PDF action.\n  await page.getByLabel("Cari pokok iman").fill("Allah");\n  await expect\n    .poll(async () => page.locator(".faith-row-heading").count())\n    .toBeLessThan(initialCount);\n  await page.getByLabel("Cari pokok iman").fill("");\n\n  // Summary and notes remain available as the explicit secondary action.\n  const summaryButton = page.getByRole("button", {\n    name: "Buka ringkasan dan catatan pokok iman 2",\n    exact: true,\n  });\n  await summaryButton.click();\n  const summary = page.getByRole("dialog", { name: "Pokok 2" });\n  await expect(summary).toBeVisible();\n  await summary.getByRole("button", { name: /Catatan pribadi/ }).click();\n  await page\n    .getByRole("dialog", { name: "Catatan pokok iman" })\n    .getByRole("textbox")\n    .fill("Renungan dari pokok dasar kepercayaan.");\n  await page.getByRole("button", { name: "Simpan catatan" }).click();\n  await expect(\n    page.getByRole("status").filter({ hasText: "disimpan" }),\n  ).toBeVisible();\n\n  await page.reload();\n  await expect(\n    page.getByRole("region", { name: "Dasar Kepercayaan" }),\n  ).toBeVisible({ timeout: 15_000 });\n  await page\n    .getByRole("button", {\n      name: "Buka ringkasan dan catatan pokok iman 2",\n      exact: true,\n    })\n    .click();\n  await page\n    .getByRole("dialog", { name: "Pokok 2" })\n    .getByRole("button", { name: /Catatan pribadi/ })\n    .click();\n  await expect(\n    page.getByRole("dialog", { name: "Catatan pokok iman" }).getByRole("textbox"),\n  ).toHaveValue("Renungan dari pokok dasar kepercayaan.");\n});''',
)
replace_once(
    smoke,
    '''test("faith read more opens PDF viewer in fullscreen overlay", async ({\n  page,\n}) => {\n  await page.goto("/GYSApp-Tauri/iman");\n  await expect(\n    page.getByRole("region", { name: "Dasar Kepercayaan" }),\n  ).toBeVisible();\n  const rows = page.locator(".faith-row-heading");\n  await expect(rows.first()).toBeVisible({ timeout: 15_000 });\n\n  await rows.first().click();\n  const modal = page.getByRole("dialog", { name: /Pokok/ });\n  await expect(modal).toBeVisible();\n\n  const readMoreBtn = modal.getByRole("button", { name: /Baca lebih lanjut/ });\n  await expect(readMoreBtn).toBeVisible();\n  await readMoreBtn.click();\n\n  const pdfOverlay = page.locator(".faith-pdf-backdrop");\n  await expect(pdfOverlay).toBeVisible();\n  await expect(pdfOverlay.locator(".faith-pdf-head")).toBeVisible();\n  await expect(pdfOverlay.locator(".faith-pdf-body")).toBeVisible();\n  await expect(\n    pdfOverlay.getByRole("button", { name: "Tutup bacaan" }),\n  ).toBeVisible();\n  await pdfOverlay.getByRole("button", { name: "Tutup bacaan" }).click();\n  await expect(pdfOverlay).toBeHidden();\n});''',
    '''test("faith row opens its PDF viewer directly in fullscreen overlay", async ({\n  page,\n}) => {\n  await page.goto("/GYSApp-Tauri/iman");\n  await expect(\n    page.getByRole("region", { name: "Dasar Kepercayaan" }),\n  ).toBeVisible();\n  const rows = page.locator(".faith-row-heading");\n  await expect(rows.first()).toBeVisible({ timeout: 15_000 });\n\n  await rows.first().click();\n  const pdfOverlay = page.locator(".faith-pdf-backdrop");\n  await expect(pdfOverlay).toBeVisible();\n  await expect(page.locator(".faith-modal-backdrop")).toHaveCount(0);\n  await expect(pdfOverlay.locator(".faith-pdf-head")).toBeVisible();\n  await expect(pdfOverlay.locator(".faith-pdf-body")).toBeVisible();\n  await expect(\n    pdfOverlay.getByRole("button", { name: "Tutup bacaan" }),\n  ).toBeVisible();\n  await pdfOverlay.getByRole("button", { name: "Tutup bacaan" }).click();\n  await expect(pdfOverlay).toBeHidden();\n});''',
)
replace_once(
    smoke,
    '''  await page.goto("/GYSApp-Tauri/lainnya?section=data");\n  await page.getByRole("button", { name: "Reset perangkat" }).click();\n  await expect(\n    page.getByText(/Preferensi dan cache GYS sudah direset/),\n  ).toBeVisible({ timeout: 15_000 });''',
    '''  await page.goto("/GYSApp-Tauri/lainnya?section=data");\n  const deviceData = page.getByTestId("device-data-tools");\n  await deviceData.locator("summary").click();\n  page.once("dialog", (dialog) => dialog.accept());\n  await deviceData\n    .getByRole("button", { name: "Reset perangkat", exact: true })\n    .click();\n  await expect(page.getByText(/Data lokal GYS sudah direset/)).toBeVisible({\n    timeout: 15_000,\n  });''',
)
